name: base-check

on: push

jobs:
  build-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make install
      - run: make lint
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}